### ISSUE TITLE
globalize2 makes too many extra queries

### ISSUE THREAD

**Issue by pupeno** [joshmh/globalize2#33]
I'm trying to lower the amount of queries my app is making and half of the queries are due to globalize2 and I couldn't found a way to minimize that.

http://stackoverflow.com/questions/3006938/fetch-main-model-and-translations-in-one-query-with-globalize2

**Comment by hukl** [comment]
I was minimizing queries by running Post.all(:include => :translations) That worked a couple of months ago before svenfuchs refactoring - it should still work. Does that help you ?

**Comment by pupeno** [comment]
It didn't work for me:

```
Page.all(:include => :translation)
  Page Load (0.4ms)   SELECT SQL_NO_CACHE * FROM `pages` 
ActiveRecord::ConfigurationError: Association named 'translation' was not found; perhaps you misspelled it?
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:115:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:114:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:91:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:1550:in `find_every'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in `find'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:635:in `all'
        from (irb):2
```

**Comment by hukl** [comment]
uhm try the plural: :translations

**Comment by pupeno** [comment]
I actually tried both, not sure why I pasted the singular one.

```
Page.all(:include => :translations)
  Page Load (0.3ms)   SELECT SQL_NO_CACHE * FROM `pages` 
ActiveRecord::ConfigurationError: Association named 'translations' was not found; perhaps you misspelled it?
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:115:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:114:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:91:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:1550:in `find_every'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in `find'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:635:in `all'
        from (irb):3
```

**Comment by hukl** [comment]
okay sorry so its page_translations i guess - look it up in your schema ;)

**Comment by pupeno** [comment]
hukl, are you meaning just a plain old Rails :include? I've tried that, but it didn't work, even though the table exist, the model and the association seem not to, there's no PageTranslation model:

```
Page.all(:include => :page_translations)
  Page Load (13.8ms)   SELECT SQL_NO_CACHE * FROM `pages` 
ActiveRecord::ConfigurationError: Association named 'page_translations' was not found; perhaps you misspelled it?
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:115:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:114:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:91:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:1550:in `find_every'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in `find'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:635:in `all'
        from (irb):4
```

**Comment by hukl** [comment]
http://github.com/hukl/cccms/blob/master/app/models/page.rb

Not sure though if its using the latest globalize version

**Comment by pupeno** [comment]
I'm sorry, I'm not sure what I'm looking at in there. Does that work with your code snippet? Your page looks like my page (regarding translations).

**Comment by hukl** [comment]
come on - read the source luke - its really not that hard … 

http://gist.github.com/432818

**Comment by pupeno** [comment]
That might have worked in an old version of globalize2, but it doesn't work anymore.

```
ruby-1.8.7-p174 > Page.all(:include => [:page_translations])
  Page Load (22.3ms)   SELECT SQL_NO_CACHE * FROM `pages` 
ActiveRecord::ConfigurationError: Association named 'page_translations' was not found; perhaps you misspelled it?
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:115:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:114:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:91:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:1550:in `find_every'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in `find'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:635:in `all'
        from (irb):5
ruby-1.8.7-p174 > Page.all(:include => [:translations])
  Page Load (2.5ms)   SELECT SQL_NO_CACHE * FROM `pages` 
ActiveRecord::ConfigurationError: Association named 'translations' was not found; perhaps you misspelled it?
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:115:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activesupport-2.3.5/lib/active_support/ordered_hash.rb:97:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:114:in `preload_one_association'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:91:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `each'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/association_preload.rb:90:in `preload_associations'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:1550:in `find_every'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in `find'
        from /Users/pupeno/.rvm/gems/ruby-1.8.7-p174@lemonfrog/gems/activerecord-2.3.5/lib/active_record/base.rb:635:in `all'
        from (irb):6
```

Maybe the old version set up an association, but without it, include won't ever work (adding the square brackets doesn't really change anything here).

**Comment by hukl** [comment]
Sorry but for my example I created a fresh rails app and installed globalize2 from github
