### ISSUE TITLE
Problem with factory girl in integration tests (Rails 2.3.8)

### ISSUE THREAD

**Issue by ncri** [joshmh/globalize2#55]
Hi there,

I'm using factory girl to setup models with translation tables for my integration tests. However, factory creation only works for the first test, during the setup of my second test i get the following error:

```
 1) Error:
 test_show_regular_events(EventsTest):  
 NoMethodError: undefined method `title=' for #<Event:0x1091cf520>
     /Users/nico/.rvm/gems/ruby-1.8.7-p302/gems/factory_girl-2.0.4/lib/factory_girl/proxy/build.rb:13:in `send'
     /Users/nico/.rvm/gems/ruby-1.8.7-p302/gems/factory_girl-2.0.4/lib/factory_girl/proxy/build.rb:13:in `set'
     /Users/nico/.rvm/gems/ruby-1.8.7-p302/gems/factory_girl-2.0.4/lib/factory_girl/attribute/dynamic.rb:15:in `add_to'
```

where title is a translated attribute.

Here is the event factory that causes the problem:

```
 FactoryGirl.define do

   factory :event do
     title                             { Factory.next(:title) }            # translated attribute
     description                "Event Description"             # translated attribute
     ....
     (other fields, some translated, some not)
     ....
   end

 end
```

So it seems somehow globalize doesn't attach the title attribute to the event after the first test run.

Any help is greatly appreciated!

Nico

**Comment by ncri** [comment]
Got it fixed, the problem was config.cache_classes was false... Nevermind ;-)
